### ISSUE TITLE
Binary outcome

### ISSUE THREAD

**Issue by bwrowland** [MCFpy/mcf#1]
Thank you @hannahbus and @hbodory for an amazing and beautifully documented package. 
One thing I was hoping to understand is whether the outcome variable can be discrete (specifically binary) instead of continuous as in example supplied in the docs?

**Comment by hannahbus** [comment]
@bwrowland, we are happy to hear that you are enjoying the mcf package and always happy to take questions. Many thanks for your contribution!

Regarding your question: The mcf also works with binary outcomes. The derivation of the splitting rule or weights-based inference in [Lechner (2019)](https://arxiv.org/abs/1812.09487) does not hinge on distributional assumptions of the outcome. When using local centering in the binary setting, it is theoretically possible to get estimated treatment effects outside the valid range. Please do not hesitate to reach out, should you encounter this issue.  

For an example you may wish to check out [Boller, Lechner and Okasa (2021)](https://arxiv.org/abs/2104.04601). They use the mcf in a binary outcome setting to examine the causal effect of doing sports on success in online dating markets.

**Comment by joostbollens** [comment]
@hannahbus , indeed a nicely documented package. I have already been experimenting a bit with the example programme from your tutorial, and it works without any problem. However, as soon as we scale up to a problem with more observations and features, sooner or later it crashes. Our IT department indicated to me that this is probably due to the environment I am working in: a docker environment on a workbench. More specifically, ray would not work well in this context.

They advise me to either switch to bare metal or move out to a cloud environment. The latter is far from obvious for privacy reasons.

What I actually wanted to ask, could you give an indication of what kind of environment you guys use to run somewhat larger samples, e.g. how much memory, how many cores etc? Thanks in advance, and definitely continue working on this nice package!
